project_name: "redirect-to"
builds:
  - binary: redirect
    main: cmd/redirect/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - "reddec/redirect:latest"
      - "reddec/redirect:{{ .Tag }}"
      - "reddec/redirect:v{{ .Major }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
snapcrafts:
  - name: redirect-to
    publish: true
    summary: Simple, very fast, in a single binary, with web UI HTTP redirect service
    description: |
      Simple, very fast, in a single binary, with web UI HTTP redirect service.
      Contains embedded UI that allows you check add/update/remove rules online and
      check how many hits you rules collected
    grade: stable
    confinement: strict
    license: MIT
    apps:
      redirect-to:
        plugs: ['network-bind']
        command: redirect

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - homepage: https://github.com/reddec/redirect
    description: Simple, very fast, in a single binary, with web UI HTTP redirect service
    maintainer: RedDec <owner@reddec.net>
    license: MIT
    formats:
      - deb